src/Lexers/ModelLexer.php
src/Translators/Rules.php
tests/Feature/Lexers/ModelLexerTest.php
tests/Feature/Translators/RulesTest.php
tests/fixtures/definitions/model-modifiers.bp
tests/fixtures/migrations/modifiers.php

- if the dataType is string and the column name starts with 'email', the ```string``` rule gets replaced with the ```email``` rule
- if the dataType is string and the column name is 'password', the ```string``` rule gets replaced with the ```password``` rule
- If the dataType is numeric the ```numeric``` rule is added. If the dataType is unsigned, ```gt:0``` is also added
- added `in:` rule with attributes for enums and sets
- added `date` rule for dataTypes date, datetime and datetimetz
Issue #17 
Thanks JMac, Loving the streams

Adds various validation rules based on column name and dataType

---

README.md

I am not sure if there is anything you want to include in PRs, but this was just a quick update to the Readme to include the flash example.

Update readme to include flash example

---

src/Generators/ModelGenerator.php
tests/Feature/Generator/ModelGeneratorTest.php
tests/fixtures/definitions/soft-deletes.bp
tests/fixtures/migrations/soft-deletes.php
tests/fixtures/models/comment.php

Fix multiple SoftDeletes trait

---

src/Blueprint.php
src/BlueprintCommand.php
src/BlueprintServiceProvider.php
src/EraseCommand.php
tests/Feature/Generator/ControllerGeneratorTest.php
tests/Feature/Generator/FactoryGeneratorTest.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/Feature/Generator/ModelGeneratorTest.php
tests/Feature/Generator/RouteGeneratorTest.php

This will add a basic `blueprint:erase` to remove the generated files from the last `blueprint:build` command.
This can not reliably erase changes made to existing files. So while this command is helpful, running `blueprint:build` from a clean working state and using version control to erase changes will always be best.

Add erase command

---

src/BlueprintCommand.php
src/BlueprintServiceProvider.php
src/Builder.php
tests/Unit/BuilderTest.php

By registering Blueprint as a singleton, users may completely override their own implementations or resolve the shared instance to register their own generators.

Register Blueprint as singleton for extensibility

---

src/Generators/FactoryGenerator.php

Noticed longtext type results in an empty faker value in the factory generation.

Add support for longtext in fakeableTypes

---

src/Generators/MigrationGenerator.php
tests/fixtures/migrations/comments.php
tests/fixtures/migrations/identity-columns.php
tests/fixtures/migrations/modifiers.php
tests/fixtures/migrations/posts.php
tests/fixtures/migrations/readme-example.php
tests/fixtures/migrations/relationships.php
tests/fixtures/migrations/soft-deletes.php
tests/fixtures/migrations/with-timezones.php

If applied, this pull request will:
| Column Types| Description | 
| --: | :-- |
|`increments` | Auto-incrementing UNSIGNED INTEGER (primary key) equivalent column.|
|`bigIncrements` | Auto-incrementing UNSIGNED BIGINT (primary key) equivalent column.|
|`unsignedBigInteger` | UNSIGNED BIGINT equivalent column.|

Fix the migration datatype of an `id` column

---

src/Generators/FactoryGenerator.php
tests/Feature/Generator/FactoryGeneratorTest.php
tests/fixtures/definitions/phone.bp
tests/fixtures/factories/phone.php

fixes #59 
> ```
> models:
>   Category:
>     category_uuid: string:200
>     name: string:200
>     status: enum:ACTIVE,NONACTIVE
> ```
> 
> ...factory file is fail
> 
> ```
> <?php
> 
> /** @var \Illuminate\Database\Eloquent\Factory $factory */
> 
> use App\Category;
> use Faker\Generator as Faker;
> 
> $factory->define(Category::class, function (Faker $faker) {
>     return [
>         'category_uuid' => $faker->word,
>         'name' => $faker->name,
>         'status' => $faker->,
>     ];
> });
> ```
> [Issue #59](https://github.com/laravel-shift/blueprint/issues/59#issue-556787160)

ENUM and SET datatypes for FactoryGenerator

---

src/Generators/FactoryGenerator.php
tests/fixtures/definitions/model-modifiers.bp
tests/fixtures/factories/model-modifiers.php
tests/fixtures/migrations/modifiers.php

support precision and scale for float and decimal columns in factory generator

---

src/Generators/FactoryGenerator.php
tests/fixtures/definitions/post.bp
tests/fixtures/factories/post-configured.php
tests/fixtures/factories/post.php

`FactoryGenerator.php` correctly generates `$faker->text` for `longtext`.

fix: mismatched key casing

---

src/Generators/FactoryGenerator.php
src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
src/Lexers/ModelLexer.php

I took a stab at #4.
You said:
> I want to determine a streamlined syntax for the latter as well as supporting existing models.
I'm not sure what I've done correlates to what you had envisioned, but this might be a push in the right direction.
Here's an example:
```
models:
Order:
user_id: id
subscription_id: id
price: float
Subscription:
user_id: id
title: string
description: longtext
price: float
relationships: hasMany:order_id,hasOne:duration_id
Duration:
title: string
months: int
```
When the word 'many' appears in the hasMany/hasOne part of the relationships line, the string between the following colon and `_id` will be pluralized.
This generates this Plan model;
```
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Plan extends Model
{
/**
* The attributes that are …
```

Generate model relationships

---

composer.json
composer.lock
src/BlueprintServiceProvider.php
src/Builder.php
src/Commands/BlueprintCommand.php
src/Commands/EraseCommand.php
src/Commands/TraceCommand.php
src/Generators/Statements/FormRequestGenerator.php
src/Generators/TestGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generator/Statements/FormRequestGeneratorTest.php
tests/Feature/Generator/TestGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/Unit/BuilderTest.php
tests/fixtures/definitions/reference-cache.bp
tests/fixtures/form-requests/reference-cache.php
tests/fixtures/tests/reference-cache.php

This new `blueprint:trace` command allows developers to load existing models into Blueprint to reference when building new components. It also automatically tracks new models generated by `blueprint:build`
The combination makes Blueprint more beneficial for generating code within existing applications. It also has use cases outside of generating new code, including:
- Consolidating many migrations into a smaller set of _create_ migrations which may improve build times.
- Modernizing migration syntax to use new shorthands for cleaner code.
- Regenerating `casts`, `dates`, or `@property` code for Models
Newly definite models will also take precedence over an existing model. This way it is easy to regenerated a model with Blueprint.

New command to load existing models for reference

---

README.md

While using Laravel Blueprint, I discovered the `blueprint:erase` command and found it very useful.  
This PR includes a quick update the docs to highlight the additional commands beyond the main `build` command to bring more visibility to these tools.

Add additional console commands to Readme

---

src/Blueprint.php
tests/Feature/BlueprintTest.php

So the Blueprint::relativeNamespace function was too greedy with using str_replace. Any other instance of the string App in the fully qualified class name pass would be stripped out. So App\Appointments would become ointments etc. I added a test. Hopefully this helps.

suggested fix for relativeNamespace function

---

src/Generators/ModelGenerator.php
stubs/model/hidden.stub
tests/Feature/Generator/ModelGeneratorTest.php
tests/fixtures/definitions/nested-components.bp
tests/fixtures/factories/nested-components.php
tests/fixtures/models/nested-components.php

This PR will add a `$hidden` attribute to models if the columns include `password` or `remember_token`. The same values as in the default Laravel `User.php`.
Mentioned in #92

Add $hidden attribute to Models

---

composer.json
src/Generators/TestGenerator.php
tests/fixtures/tests/readme-example.php
tests/fixtures/tests/reference-cache.php

Support v1.0 of jasonmccreary/laravel-test-assertions

---

src/Generators/MigrationGenerator.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/fixtures/definitions/optimize.bp
tests/fixtures/migrations/optimize.php

Any unsignable datatype that has the unsigned modifier specified will be optimized to it's `unsigned[type]` corresponding datatype.
ie: 
```
foo: integer unsigned
```
Becomes:
```
$table->unsignedInteger('foo');
```
And so forth.
Closes #5

Optimize unsigned columns

---

src/Generators/Statements/ResourceGenerator.php
tests/Feature/Generator/Statements/ResourceGeneratorTest.php
tests/fixtures/definitions/resource-statements.bp
tests/fixtures/resources/user.php

feat: generate resource `toArray` for non-hidden columns

---

.gitattributes

Using a `.gitattributes` file seems to be the common way to exclude files from being part of the package during a `composer install`.
This closes #119 and provides a foundation for excluding other files in the future.

Exclude files from package export

---

src/Generators/ControllerGenerator.php
src/Generators/RouteGenerator.php
src/Generators/TestGenerator.php
tests/Feature/Generator/ControllerGeneratorTest.php
tests/Feature/Generator/RouteGeneratorTest.php
tests/fixtures/controllers/respond-statements.php
tests/fixtures/definitions/respond-statements.bp
tests/fixtures/routes/respond-statements.php
tests/fixtures/tests/respond-statements.php

fix: controller namespace

---

src/Blueprint.php
tests/Feature/BlueprintTest.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/fixtures/definitions/uuid-shorthand.bp
tests/fixtures/migrations/uuid-shorthand.php

Allows `uuid` shorthand in model definitions which will expand to `id: uuid primary`.
---
Closes #77

Support uuid primary key shorthand

---

src/Generators/ControllerGenerator.php

I tried to add a namespace for Models, but there was a namespacing error in the controller file.
use App\Models\Post; 
use App\Admin\Post; 
```yaml
models:
Models\Post:
title: string:400
content: longtext
controllers:
Admin\Post:
index:
query: all
render: post.index with:posts
store:
validate: title, content
save: post
flash: post.title
redirect: post.index
```
Those changes should solve the problem as I tried it locally
Thanks!

fix models namespace issues

---

src/Translators/Rules.php
tests/Feature/Translators/RulesTest.php

A `Column` with data type `json` will now receive the `json` validation rule.

add json rule to json columns

---

src/Generators/FactoryGenerator.php
src/Generators/MigrationGenerator.php
src/Models/Column.php
tests/Unit/Models/ColumnTest.php
tests/fixtures/definitions/phone.bp
tests/fixtures/factories/phone.php

Right now if we use a morphs column type like:
```
foo: morphs
```
We get a factory like this:
This PR will add those 2 fields (id and type) for morphs.
For a column definition like `morphs nullable` it will not generate factory fields for those 2 columns.
An `isNullable()` helper method for the Column Model.
Questions:
- Should we add a factory definition for a nullable column? 
In my opinion we shouldn't. If a column is nullable, the factory should not have a definition for that column, otherwise we don't have a way to set it to null. If we send a null value for a key, the factory will generate the value for that key.
- Should we add support for  `nullableMorphs`, `nullableUuidMorphs`, `nullableTimestamps` column definitions that are availabe on Laravel.
So right now this works:
``` …
```

Fix factory generation for morphs column type

---

src/Generators/MigrationGenerator.php

This is a fix for #136 
Get lowercase $segment for column name
Sets the default dataType as bigInteger
Sets the filename to _pivot_table.php - I prefer this convention instead of removing from classname but could go either way there.

Fixes pivot table filename and column references

---

src/Blueprint.php
tests/Feature/BlueprintTest.php

> `$` By default, the match must occur at the end of the string or before `\n` at the end of the string; in multiline mode, it must occur before the end of the line or before `\n` at the end of the line.
> https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference
closes #138

fix: update regular expression to support windows

---

.github/workflows/build.yml
.github/workflows/phplint.yml
src/Blueprint.php
src/Commands/TraceCommand.php
src/FileMixins.php
src/Generators/ControllerGenerator.php
src/Generators/ModelGenerator.php
src/Generators/Statements/EventGenerator.php
src/Generators/Statements/FormRequestGenerator.php
src/Generators/Statements/JobGenerator.php
src/Generators/Statements/MailGenerator.php
src/Generators/Statements/ResourceGenerator.php
src/Generators/Statements/ViewGenerator.php
tests/TestCase.php

This PR fixes the build for Windows by normalizing output to use `PHP_EOL` and the Unix directory separator throughout.
*Note:* while the _stubs_ and _fixtures_ use Unix line endings, PHP seems to handle this conversion implicitly on read.
---
Supersedes #153

Fix Windows end of line and path issues

---

src/Generators/TestGenerator.php
tests/Feature/Generator/TestGeneratorTest.php
tests/fixtures/definitions/full-crud-example.bp
tests/fixtures/tests/full-crud-example.php

Under certain combinations of statements and controller actions, some of the code generated for the test case setup was duplicated. Particularly the `factory` generation.
This simply adds some good old collection filtering to ensure only unique lines are generated.
---
Supersedes #144

Only generate unique test setup statements

---

config/blueprint.php
src/Generators/ModelGenerator.php
stubs/model/guarded.stub
tests/Feature/Generator/ModelGeneratorTest.php
tests/fixtures/definitions/model-guarded.bp
tests/fixtures/models/model-guarded.php

Use `$guarded` instead of `$fillable` when configuration option is set.
---
Closes #148

Allow configuration to use `$guarded = [];`

---

src/Generators/TestGenerator.php
src/Lexers/ControllerLexer.php
src/Models/Statements/EloquentStatement.php
src/Models/Statements/QueryStatement.php
tests/Feature/Generator/ControllerGeneratorTest.php
tests/Feature/Generator/ModelGeneratorTest.php
tests/Feature/Generator/TestGeneratorTest.php
tests/fixtures/controllers/certificate-controller.php
tests/fixtures/controllers/certificate-type-controller.php
tests/fixtures/definitions/pascal-case.bp
tests/fixtures/models/certificate-pascal-case-example.php
tests/fixtures/models/certificate-type-pascal-case-example.php
tests/fixtures/tests/certificate-pascal-case-example.php
tests/fixtures/tests/certificate-type-pascal-case-example.php

I haven't implemented the tests for the generated resources because of the problem in the issue #172
Also because of the issue #172 the generated tests looks incomplete.
Closes #171

fix: controller/resource generation with PascalCase definition

---

src/Lexers/StatementLexer.php
src/Models/Statements/EloquentStatement.php
tests/Feature/Lexers/StatementLexerTest.php
tests/Unit/Models/Statements/EloquentStatementTest.php
tests/fixtures/controllers/certificate-controller.php
tests/fixtures/controllers/certificate-type-controller.php
tests/fixtures/controllers/custom-models-namespace.php

While the `update: model` syntax was _lexed_, it was not outputting the generated code.
I'd still like to support pairing this with a `validate` statement for additional developer convenience. But I'll open a separate issue for that as this resolves the initial bug.
---
Closes #185

Generate basic code for Eloquent update statements

---

src/Generators/Statements/FormRequestGenerator.php
tests/Feature/Generator/Statements/FormRequestGeneratorTest.php
tests/fixtures/definitions/model-reference-validate.bp
tests/fixtures/form-requests/certificate-store.php
tests/fixtures/form-requests/certificate-update.php

I think this solution can be improved.
---
Closes #172

Support model reference in validate statement to validate all columns

---

src/Generators/ModelGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generator/FactoryGeneratorTest.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/Feature/Generator/ModelGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/fixtures/definitions/foreign-key-shorthand.bp
tests/fixtures/factories/foreign-key-shorthand.php
tests/fixtures/migrations/foreign-key-shorthand.php
tests/fixtures/models/foreign-key-shorthand-phpdoc.php

This adds support for using a `foreign` _shorthand_ when definition models to automatically be treated as a belongs to relationship.
**Before**
```yaml
models:
Comment:
post_id: id foreign
```
**After**
```yaml
models:
Comment:
post_id: foreign
```
---
Closes #219

Support for foreign data type shorthand

---

src/Generators/RouteGenerator.php
src/Lexers/ControllerLexer.php
tests/Feature/Generator/RouteGeneratorTest.php
tests/Feature/Lexers/ControllerLexerTest.php
tests/fixtures/definitions/multiple-resource-controllers.bp
tests/fixtures/routes/multiple-resource-controllers-api.php
tests/fixtures/routes/multiple-resource-controllers-web.php

Fixes bug introduced in #210 where all `resource` controller were generating API routes.
---
Closes #225

Fix resource always generating API routes

---

src/Generators/FactoryGenerator.php
src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
stubs/factory.stub
tests/Feature/Generator/FactoryGeneratorTest.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/Feature/Generator/ModelGeneratorTest.php
tests/fixtures/factories/resource-statements.php
tests/fixtures/migrations/resource-statements.php
tests/fixtures/models/resource-statements.php

- Add the shorthand to `Blueprint::parse`
- Update the `MigrationGenerator` for `rememberToken`
- Update the `FactoryGenerator` for `remember_token` columns
- Update the `ModelGenerator` to hide the attribute
Closes #228

feat: add support for rememberToken() shorthand

---

config/blueprint.php
src/Generators/MigrationGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/fixtures/definitions/nullable-chaining.bp
tests/fixtures/migrations/nullable-chaining-laravel6.php
tests/fixtures/migrations/nullable-chaining.php

- Update `ModelLexer` to parse `onDelete` modifier
- Update `MigrationGenerator` to generate  both `cascade` and `set_null` clauses.
- Update fixtures to Test `MigrationGenerator`.
Usage:
```
models:
Cart:
name: string
user_id: id foreign nullable ondelete:set_null
```
Closes #213

feat: add support for `cascade`, `set null`, `restrict`, and `no action` for onDelete actions

---

src/Blueprint.php
tests/Feature/BlueprintTest.php

Closes #236 
Currently there is no way to override the default registered generators. This PR adds a `swapGenerator` method that was discussed in #236 with a matching test!

Add method to swap registered generators

---

src/Commands/TraceCommand.php

fix: ignore models that extend Jenssegers\Mongodb\Eloquent\Model

---

src/Lexers/ControllerLexer.php
tests/Feature/Lexers/ControllerLexerTest.php
tests/fixtures/definitions/multiple-resource-controllers.bp
tests/fixtures/routes/multiple-resource-controllers-api.php
tests/fixtures/routes/multiple-resource-controllers-web.php

- confirm all resource methods for an API controller are prefixed with `api.`
- if you are mixing "api" and "web" routes in the same controller, then they should all be "web" routes.
eg.
`draft.yaml`:
```yaml
controllers:
Category:
resource: index, api.destroy
```
`web.php`:
```yaml
Route::resource('category', 'CategoryController')->only('index', 'destroy');
```
closes #241
supersedes pr #242

fix: confirm api resource methods

---

src/Commands/BuildCommand.php

2 Changes:
- If the draft file is not found it will exit the command, preventing exceptions.
Before:
After:
- Add info for the `draft argument
Right now there's no info about the optional argument:
With this PR we will have the info for the `draft` argument:

Build command improvements

---

src/Generators/TestGenerator.php
tests/Feature/Generator/TestGeneratorTest.php
tests/fixtures/drafts/models-with-custom-namespace.yaml
tests/fixtures/tests/models-with-custom-namespace.php

This pull request is a quick fix for the wrong model imports in tests.
But as @jasonmccreary mentioned in #254 a better solution would be a central registry for models.
---
Closes #254

fix: wrong model imports in tests

---

src/Generators/FactoryGenerator.php
tests/Feature/Generator/FactoryGeneratorTest.php
tests/fixtures/drafts/factory-smallint-and-tinyint.yaml
tests/fixtures/factories/factory-smallint-and-tinyint.php

This pull request fixes the factory generation for `smallInteger` and `tinyInteger` dataTypes.
---
Closes #255

fix: factory generation for smallInteger and tinyInteger dataTypes

---

src/Blueprint.php
src/Commands/EraseCommand.php
tests/Feature/BlueprintTest.php

Since the `.blueprint` file uses a simple array (list) to output generated files, the striping of dashes in `Blueprint::parse` returns a string when called by the `erase` command.
This adds an optional flag to disable that behavior so it may be used internally when parsing the `.blueprint` file.
---
Fixes #270

Allow use of dashes in .blueprint

---

README.md
src/Generators/TestGenerator.php
src/Translators/Rules.php
tests/Feature/BlueprintTest.php
tests/Feature/Generator/Statements/MailGeneratorTest.php
tests/Feature/Lexers/StatementLexerTest.php
tests/Feature/Translators/RulesTest.php
tests/fixtures/controllers/readme-example.php
tests/fixtures/drafts/readme-example.yaml
tests/fixtures/factories/fake-nullables.php
tests/fixtures/form-requests/form-request-configured.php
tests/fixtures/mailables/mail-configured.php
tests/fixtures/migrations/readme-example.php
tests/fixtures/models/readme-example-phpdoc.php
tests/fixtures/models/readme-example.php
tests/fixtures/tests/readme-example.php

This corrects the example in the `README` to properly generate an `author` relationship on the `Post` model.
In doing so this revealed a few boundary cases, including the generated code for the `exists` validation rule when the `id` attribute is set. As well as incorrect setup for the test case.
Also found a bug for the generated assertions when using a Notification. I have opened a new issue for that in #274.
---
Fixes #248

Updates for more README example

---

src/Commands/TraceCommand.php
src/EnumType.php
src/Generators/MigrationGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/Unit/EnumTypeTest.php
tests/fixtures/drafts/enum-options.yaml
tests/fixtures/migrations/enum-options.php

This adds enum support when running the `trace` command on existing models which define a column of type `enum`. 
**Note:** while other RDBMSes may _support_ the `enum` type, this is currently only tested on MySQL.
---
Fixes #218

Register custom type to support MySQL enums

---

src/Blueprint.php
src/Builder.php
src/Commands/BuildCommand.php
src/Contracts/Generator.php
src/Generators/ControllerGenerator.php
src/Generators/FactoryGenerator.php
src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
src/Generators/RouteGenerator.php
src/Generators/SeederGenerator.php
src/Generators/Statements/EventGenerator.php
src/Generators/Statements/FormRequestGenerator.php
src/Generators/Statements/JobGenerator.php
src/Generators/Statements/MailGenerator.php
src/Generators/Statements/NotificationGenerator.php
src/Generators/Statements/ResourceGenerator.php
src/Generators/Statements/ViewGenerator.php
src/Generators/TestGenerator.php
tests/Feature/BlueprintTest.php
tests/Unit/BuilderTest.php

Closes #247 
This is an implementation of the `--only` and `--skip` command line options for the `blueprint:build` command.
Both commands take a comma separated list of 'file classes' (for the lack of a better word), those being:
* controllers
* factories
* migrations
* models
* routes
* seeders
* tests
* events
* requests
* jobs
* mails
* notifications
* resources
* views
The command passes the string values to `Blueprint\Builder::execute()` as additional, optional parameters `$only` and `$skip`. The action body will convert these strings to arrays, and passes those arrays to `$blueprint->generate()` alongside of the `$registry`. This action iterates over the registered  `$this->generators` and for each one call `output()`, again passing the `$tree`, `$only` and `$skip`.
Each registered …

Fix #247: Implements blueprint:build --only and --skip

---

src/Generators/TestGenerator.php
tests/fixtures/drafts/model-reference-validate.yaml
tests/fixtures/tests/api-shorthand-validation.php
tests/fixtures/tests/certificate-pascal-case-example.php

This finalizes #207 and supersedes the work done in #281 to bring full support for properly using factories to set up fake data within tests for referenced models.

Use factory for referenced relationships in validation statements

---

src/Lexers/ModelLexer.php
tests/Feature/Lexers/ModelLexerTest.php

This fixes #285, also added the `default:0` modifier as a test case.

Use strict check on null instead of empty()

---

src/Generators/TestGenerator.php
tests/fixtures/tests/api-shorthand-validation.php
tests/fixtures/tests/certificate-pascal-case-example.php
tests/fixtures/tests/certificate-type-pascal-case-example.php
tests/fixtures/tests/models-with-custom-namespace.php

There were no assertions being generated for `resource` statements. This adds some basic checks which the developer can fill in to strengthen.

Generate simple assertions for resource statements

---

src/Generators/ControllerGenerator.php
src/Models/Statements/EloquentStatement.php
tests/fixtures/controllers/certificate-controller.php
tests/fixtures/controllers/certificate-type-controller.php
tests/fixtures/controllers/custom-models-namespace.php

This will generate a statement to fill an existing model with the validated request data on _update_. **Note**, this is rather nuanced, only for shorthand references where validation is used.
For example:
```yaml
update:
validate: post
update: post
```
But not:
```yaml
update:
update: post
```
Or:
```yaml
update:
validate: other, columns
update: name, title, post
```
---
Fixes #292

Update with request data when using validation

---

src/Generators/Generator.php
src/Generators/StatementGenerator.php
src/Generators/Statements/EventGenerator.php
src/Generators/Statements/MailGenerator.php
src/Generators/Statements/NotificationGenerator.php
src/Models/Statements/FireStatement.php

By introducing a property for `$new_instance`, we can easily extract the duplicated code between generators and pull them up to an abstract generator class.
Even If we need to customize any of the extracted methods in the future, we can override them so I change the visibility of these methods to protected.
Hope you will find this useful.
I will start working on the `Tree` class as we discussed before, and submit a PR tonight 👍

extract common logic to abstract generator

---

phpunit.xml

Hi again!
I enjoyed refactoring the codebase so I can understand the current features before helping introduce a new one or pick a community requested enhancements.
Before going further with extra enhancements, I would like to take care of the `tests` suite, so I enabled the code coverage by adding the whitelisting section to the `phpunit.xml` config file.
The current code coverage reports below show that classes especially the commands and the top-level classes are not well-tested. I just want to double-check if you are interested to cover them?
In addition to that, I think the `TraceCommand` encapsulate too many concerns and the private method's logic need to be moved to another class to make the command lighter? if yes, what would you name the new class?
I asked about the …

Add whitelist section to enable code coverage

---

src/BlueprintServiceProvider.php
src/Builder.php
src/Commands/BuildCommand.php
tests/Feature/Commands/BuildCommandTest.php
tests/Unit/BuilderTest.php

In order to test the BuildCommand, I changed some code to make the `Builder` and `BuildCommand` more testable
1. Inject `Builder` to `BuildCommand` nested of Static method invocation to unit test the command. We can also provide e Builder facade and return the static method invocation if needed.
1. Replace `file_exists` with `$this->files->exists` to allow tests code to mock it.
1. Replace `exit(1)` with `return 1` so we can use `assertExitCode(1)` and prevent the command from killing the test command.
1. Simplifying `defaultDraftFile` is not related to the test code, and I can revert the change if you like the old style.
Waiting for your feedback, and if everything goes ok, please select the next candidate to be tested.
Have a nice day 👍

BuildCommand tests

---

src/Blueprint.php
src/Builder.php
src/Commands/BuildCommand.php
src/Generators/MigrationGenerator.php
tests/Feature/BlueprintTest.php
tests/Feature/Commands/BuildCommandTest.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/Unit/BuilderTest.php

As per #265, supports `blueprint:build --overwrite-migrations`
Was a little awkward passing options down from the command to a generator, would be worth refactoring if other options for generators will be supported in the future.

Migrations with fixed timestamp

---

config/blueprint.php
src/Generators/RouteGenerator.php
tests/Feature/Generator/RouteGeneratorTest.php
tests/fixtures/drafts/routes-tuples.yaml
tests/fixtures/routes/routes-tuples.php

I was unsure which approach to take, but I ended up with reading out the actual value from the UrlGenerator class itself, rather than trying to analyze the RouteServiceProvider. Seemed like the most stable solution to me.
Fixes #321

Add support for tuple route generation

---

src/BlueprintServiceProvider.php
src/Commands/TraceCommand.php
src/Tracer.php
tests/Feature/Commands/EraseCommandTest.php
tests/Feature/Commands/TraceCommandTest.php

Sorry for suggesting too many conflicting ideas. 😕 
When I start thinking about the big picture and think how must we test the trace command itself, I realized that the command includes the full implementation in contrast to the build command which depends on `Buillder` class.
The PR is not ready for merging yet, but I want to make sure that you are ok with the approach of separating the command from the logic itself. If yes, this will make it easier to call the `Tracer` in other command and test if it's called or not without calling a command from another command?
I really enjoyed reading and refactoring the code, and I think I'm very close to start contributing new features and community requested enhancements.

lighter trace command to increase the reusability and testability 

---

tests/Feature/Generator/ControllerGeneratorTest.php
tests/Feature/Generator/FactoryGeneratorTest.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/Feature/Generator/ModelGeneratorTest.php
tests/Feature/Generator/SeederGeneratorTest.php
tests/Feature/Generator/Statements/EventGeneratorTest.php
tests/Feature/Generator/Statements/FormRequestGeneratorTest.php
tests/Feature/Generator/Statements/JobGeneratorTest.php
tests/Feature/Generator/Statements/MailGeneratorTest.php
tests/Feature/Generator/Statements/NotificationGeneratorTest.php
tests/Feature/Generator/Statements/ResourceGeneratorTest.php
tests/Feature/Generator/Statements/ViewGeneratorTest.php
tests/Feature/Generator/TestGeneratorTest.php
tests/TestCase.php

The old stubs reference prevents me from running the test case directly in PHPStorm alone because it references a relative directory.
I add a new helper to `TestCase` to make it easier to reference stubs in test cases and modify the old tests to use it.

Stubs helper

---

src/Lexers/ModelLexer.php
tests/Feature/Generator/MigrationGeneratorTest.php
tests/fixtures/drafts/columns-with-comments.yaml
tests/fixtures/migrations/columns-with-comments.php

- single-quote and double-quote string accepted.
closes #344

Generate migration columns with comments

---

tests/Feature/Generator/ModelGeneratorTest.php
tests/fixtures/drafts/alias-relationships.yaml
tests/fixtures/models/alias-relationships.php

- Testing the syntax `{belongsTo|hasOne|hasMany}: {class_name}:{method_name}` is supported, to "alias" relationships .
- Resolve #294 
**draft.yaml:**
```yaml
models:
Salesman:
name: string
relationships:
hasOne: User:Lead
hasMany: class_name:method_name
belongsTo: class_name:method_name
```
**Output:**
```php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Salesman extends Model
{
/**
* The attributes that are mass assignable.
*
* @var array
*/
protected $fillable = [
'name',
];
/**
* The attributes that should be cast to native types.
*
* @var array
*/
protected $casts = [
'id' => 'integer',
];
public function lead()
{
return $this->hasOne(\App\User::class);
}
public function methodNames()
{
return $this->hasMany(\App\ClassName::class);
}
public function methodName() …
```

test: Aliasing method names for an Eloquent relationship

---

src/Generators/MigrationGenerator.php
tests/fixtures/migrations/belongs-to-many-key-constraints-laravel6.php
tests/fixtures/migrations/belongs-to-many-key-constraints.php
tests/fixtures/migrations/belongs-to-many-pivot-key-constraints-laravel6.php
tests/fixtures/migrations/belongs-to-many-pivot-key-constraints.php
tests/fixtures/migrations/foreign-key-on-delete-laravel6.php
tests/fixtures/migrations/foreign-key-on-delete.php
tests/fixtures/migrations/foreign-key-shorthand.php
tests/fixtures/migrations/model-key-constraints.php
tests/fixtures/migrations/nullable-chaining-laravel6.php
tests/fixtures/migrations/nullable-chaining.php
tests/fixtures/migrations/relationships-constraints-laravel6.php
tests/fixtures/migrations/relationships-constraints.php
tests/fixtures/migrations/unconventional-foreign-key.php

- generate migrations with the syntax to disable foreign key constraints when referencing another table.
- supports Laravel 6 & 7 foreign key syntax.
- resolve #208 
```php
class CreateStatesTable extends Migration
{
/**
* Run the migrations.
*
* @return void
*/
public function up()
{
Schema::disableForeignKeyConstraints();
Schema::create('states', function (Blueprint $table) {
$table->id();
$table->string('name');
$table->foreignId('countries_id')->constrained('countries')->cascadeOnDelete();
$table->string('country_code');
$table->foreign('country_code')->references('code')->on('countries')->onDelete('cascade');
});
Schema::enableForeignKeyConstraints();
}
```

Toggle foreign key constraints for Migrations

---

stubs/view.stub
tests/Feature/Generators/Statements/ViewGeneratorTest.php
tests/fixtures/views/post.show.blade.php
tests/fixtures/views/user.create.blade.php
tests/fixtures/views/user.index.blade.php

Currently, if you: 
- Created a new app
- Install Blueprint
- Install laravel-test-assertions
- Run `php artisan blueprint:build readme-example.yaml`
- Run `php artisan migrate:refresh`
- Run `php artisan test`
The test fails with `500 error` because the `views` generated by Blueprint extend `layouts.app` which does not exist.
---
This PR: 
1. updated `stubs/view.stub` with a blade comment. devs will have a good starting point and test runs without errors.
2. updated `ViewGeneratorTest` to use fixtures instead of the inline template.

View generator test and fixtures

---

src/Generators/MigrationGenerator.php

Currently: 
---
If you run `php artisan blueprint:build` **more than once**, without the `-m|--overwrite-migrations` flag, Blueprint will generate duplicate migrations with different timestamps.
If you then run `php artisan blueprint:build -m` or `php artisan blueprint:build --overwrite-migrations`, Blueprint will overwrite **ONLY** the first migration file it finds. All other duplicate migrations with different timestamps will still exist.
PR:
---
1. Running `php artisan blueprint:build`
- Blueprint will still generate duplicate migrations with different timestamps with `php artisan blueprint:build` (for comparison,testing, etc.)
2. Running `php artisan blueprint:build -m` or `php artisan blueprint:build --overwrite-migrations`
- Blueprint will update the oldest existing migration file. …

Remove duplicates with overwrite-migrations flag

---

src/Generators/TestGenerator.php
tests/fixtures/tests/models-with-custom-namespace-laravel8.php
tests/fixtures/tests/models-with-custom-namespace.php

When using a model with `softDeletes`.
The `assertDeleted` check fails with soft deleted models.
This checks if the model has soft deletes and applies the correct assertion.
`draft.yaml` used for testing.
```
models:
Post:
title: string
softDeletes
controllers:
Post:
resource
```

The destroy test should assert for SoftDeleted

---

src/Generators/TestGenerator.php
tests/fixtures/tests/api-shorthand-validation-laravel8.php
tests/fixtures/tests/api-shorthand-validation.php
tests/fixtures/tests/certificate-pascal-case-example-laravel8.php
tests/fixtures/tests/certificate-pascal-case-example.php

When using a `date` field without time the tests need to check against a formatted date.
Otherwise when running the tests you get an error that the date string does not match a Carbon object.
I'm using this basic `draft.yaml`
```
models:
Post:
published_date: date
controllers:
Post:
resource
```
This update checks if the field type is a `date` during the test generator and includes a format. This was the simplest way I could find to check if the column was a `date`. If there was more than 1 exception, I could see refactoring this out to a Registry like for Faker.
I tested this against both Laravel 7 and 8

Set a date format on a date column for update test.

---

src/Models/Model.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/fixtures/drafts/with-path-prefix.yaml
tests/fixtures/migrations/with-path-prefix-table-name-city-region-laravel6.php
tests/fixtures/migrations/with-path-prefix-table-name-city-region.php
tests/fixtures/migrations/with-path-prefix-table-name-region-laravel6.php
tests/fixtures/migrations/with-path-prefix-table-name-region.php

Supercedes #387
---
Closes #387

fix: pivot table naming when model name contains path prefix

---

src/Generators/ModelGenerator.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/fixtures/models/all-column-types-laravel8.php
tests/fixtures/models/certificate-pascal-case-example-laravel8.php
tests/fixtures/models/readme-example-laravel8.php
tests/fixtures/models/readme-example-phpdoc-laravel8.php

Removes `$dates` property from models on L8+

---

src/Lexers/ModelLexer.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/fixtures/drafts/uuid-shorthand-invalid-relationship.yaml
tests/fixtures/migrations/uuid-shorthand-invalid-relationship.php
tests/fixtures/models/all-column-types-laravel8.php
tests/fixtures/models/all-column-types.php
tests/fixtures/models/uuid-shorthand-invalid-relationship-laravel8.php
tests/fixtures/models/uuid-shorthand-invalid-relationship.php

Fix: Invalid UUID relationships

---

src/Generators/FactoryGenerator.php
src/Generators/MigrationGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/fixtures/drafts/custom-indexes.yaml
tests/fixtures/migrations/columns-with-comments.php
tests/fixtures/migrations/custom-indexes.php

I used this`draft.yml` file.
```yaml
models:
cooltable:
coolcool: id foreign:coolcool.id index:custom_index_coolcool
foobar: id foreign:foobars.id index:custom_index_foobar
```
reverse-engineered from the generated code on #402
```php
Schema::create('cooltable', function (Blueprint $table) {
19▕             $table->id();
➜  20▕             $table->foreignId('coolcool')->constrained()->cascadeOnDelete()->index(custom_index_coolcool);
21▕             $table->foreignId('foobar')->constrained()->cascadeOnDelete()->index(custom_index_foobar);
22▕         });
```
Closes #402

fix: sanitize modifier attributes

---

src/Generators/MigrationGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/BlueprintTest.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/fixtures/drafts/model-relationships.yaml
tests/fixtures/drafts/uuid-shorthand.yaml
tests/fixtures/drafts/uuid-without-relationship.yaml
tests/fixtures/migrations/uuid-shorthand-constraint.php
tests/fixtures/migrations/uuid-without-relationship.php
tests/fixtures/models/model-relationships-laravel8.php

This PR fixes an issue reported where `uuid` columns generated a foreign key relationships. In the process of solving this, I also added a feature where `uuid` columns with a _conventional_ name automatically creates the relationship.
For example:
```yaml
models:
Subscription:
product_id: uuid
```
Creates a `belongsTo` relationship for `Product`.
---
Closes #417

Do not generate foreign key for simple UUID column

---

src/Generators/ModelGenerator.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/fixtures/drafts/optimize.yaml
tests/fixtures/migrations/optimize.php
tests/fixtures/models/optimize.php

Supersedes: #423
- Morphs 
- uuidMorphs 
- nullableMorphs 
- nullableUuidMorphs
close #422 
close #423

Add additional phpdocs annotation

---

src/Generators/FactoryGenerator.php
tests/fixtures/drafts/phone.yaml
tests/fixtures/factories/phone-laravel8.php
tests/fixtures/factories/phone.php

```
models:
Post:
tag: string:3
```
- `string:{limit}` syntax will now generate `$faker->regexify('[A-Za-z0-9]{limit}')` instead of  `$faker->word`.
Resolves #434

Add string limit for faker words

---

src/Blueprint.php
src/Generators/RouteGenerator.php
src/Lexers/ControllerLexer.php
tests/Feature/BlueprintTest.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/Feature/Generators/RouteGeneratorTest.php
tests/Feature/Lexers/ControllerLexerTest.php
tests/fixtures/controllers/invokable-controller-shorthand.php
tests/fixtures/controllers/invokable-controller.php
tests/fixtures/drafts/invokable-controller-shorthand.yaml
tests/fixtures/drafts/invokable-controller.yaml
tests/fixtures/drafts/non-cruddy.yaml
tests/fixtures/drafts/routes-tuples.yaml
tests/fixtures/drafts/shorthands.yaml
tests/fixtures/routes/invokable-controller.php
tests/fixtures/routes/non-cruddy.php
tests/fixtures/routes/routes-tuples.php

This change allows to properly generate routes for invokable controllers, by defining an `__invoke` method on a controller. 
Considering a definition like the following:
```
controllers:
Report:
__invoke:
render: report
```
Before the change, the generated route would be
`Route::get('/report', [App\HttpControllers\ReportController::class, '__invoke']);`
(or `Route::get('/user/{id}', 'ReportController@__invoke']);` without tuples).
After the change, the generated route is
`Route::get('/report', App\HttpControllers\ReportController::class);`
(or `Route::get('/report', 'ReportController');` without tuples).

Feature: invokable controllers

---

src/Generators/MigrationGenerator.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/fixtures/drafts/model-numeric-defaults.yaml
tests/fixtures/migrations/model-numeric-defaults.php

Properly output a numeric default for all numeric column data types.
---
Closes #440

Fix output of numeric defaults

---

src/Generators/FactoryGenerator.php
src/Generators/ModelGenerator.php
src/Tree.php
tests/Feature/Generators/FactoryGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/fixtures/drafts/nested-models.yaml
tests/fixtures/factories/nested-models-laravel8.php
tests/fixtures/models/nested-models-laravel8.php

Properly determine namespace for related models in Model and Factory generators. However, there may be other locations still missing...
---
Closes #442

Generate correct reference for nested models

---

src/Tracer.php

While doing a `Trace` I was getting:
```
Error
Call to undefined method Doctrine\DBAL\Connection::fetchAll()
```
Changing `fetchAll` to `fetchAllAssociative` fixes the issue.
This was introduced by https://github.com/laravel-shift/blueprint/pull/409.
On DBal 2.9 source code, the `fetchAll` method has the comment `@deprecated Use fetchAllAssociative()`.
On DBal 3.0 it was removed [https://github.com/doctrine/dbal/.../src/Connection.php](https://github.com/doctrine/dbal/blob/20bcec57aae2e24b82a32a33d2e9227dde6c1bba/src/Connection.php#L766).

[BUG] Fix for deprecated `fetchAll` > `fetchAllAssociative`

---

src/Tree.php

closes #464
eg. the singular of species is species.  so no need to force `WaterSpeciesController` to reference a `WaterSpecy` model. (Currently causing the `null` error)
This will check for and return a `studly` `plural` version of the model name in the `Tree`.

Fix plural-singular modelForContext

---

src/Generators/ControllerGenerator.php
src/Models/Statements/QueryStatement.php
src/Models/Statements/ResourceStatement.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/Feature/Generators/Statements/ResourceGeneratorTest.php
tests/Feature/Lexers/StatementLexerTest.php
tests/fixtures/controllers/api-resource-pagination.php
tests/fixtures/controllers/resource-statements.php
tests/fixtures/drafts/api-resource-pagination.yaml
tests/fixtures/resources/api-post-resource.php
tests/fixtures/resources/api-resource-pagination.php

- resolves #439
- `QueryStatement` can now determine the Model from `get` and `pluck` operations.
- No longer a need to define `query: all` when you define `resource: 'paginate:{model}'`.
```diff
models:
Post:
title: string
body: text
controllers:
Post:
resource: api
index:
-      query: all
resource: 'paginate:posts'
seeders: Post
```

Fix resource pagination

---

src/Generators/TestGenerator.php
src/Tree.php
tests/Feature/Generators/TestGeneratorTest.php
tests/fixtures/drafts/call-to-a-member-function-columns-on-null.yaml
tests/fixtures/tests/call-to-a-member-function-columns-on-null-Api-PaymentControllerTest-laravel8.php
tests/fixtures/tests/call-to-a-member-function-columns-on-null-PaymentControllerTest-laravel8.php
tests/fixtures/tests/call-to-a-member-function-columns-on-null-SubscriptionControllerTest-laravel8.php
tests/fixtures/tests/call-to-a-member-function-columns-on-null-TelegramControllerTest-laravel8.php

Determine correct model for context

---

src/Generators/MigrationGenerator.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/fixtures/drafts/nullable-columns-with-foreign.yaml
tests/fixtures/migrations/nullable-columns-with-foreign.php

Hello @jasonmccreary hope to find you well.
I think I found an issue with `Blueprint` when using **foreigns**.
So here is the scenario, given the following `yaml` file:
```yaml
models:
SomeTestsMigration:
id
user_id: id foreign:users.id nullable
something: integer foreign:monsteras.id nullable
timestamps
```
This would produce the following migration: 
```php
Schema::disableForeignKeyConstraints();
Schema::create('some_tests_migrations', function (Blueprint $table) {
$table->id();
$table->foreignId('user_id')->nullable()->constrained();
$table->integer('something'); //notice here its missing the nullable modifier.
$table->foreign('something')->references('id')->on('monsteras');
$table->timestamps();
});
Schema::enableForeignKeyConstraints();
```
Blueprint does handle the nullable modifier …

allow non-id columns to be nullable when using foreign

---

src/Generators/ControllerGenerator.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/fixtures/controllers/return-type-declarations-api-resource.php
tests/fixtures/drafts/return-type-declarations-api-controller.yaml

Hello,
When I generate controllers with resource:api and with use_return_types set to true.
The return type controller is set to Response instead of the Resource
Before :
After :

FIX - return types in controller when use resource: api

---

src/Commands/TraceCommand.php
src/Tracer.php
tests/Feature/Commands/EraseCommandTest.php
tests/Feature/Commands/TraceCommandTest.php

Hi @jasonmccreary.
Until now Trace Command would read files from app path, or if set, it would read files from `config('blueprint.models_namespace')`.
This PR adds the possibility to trace models outside `app`, for instance, developers may load files from `.\vendor\...` or `.\packages\...`, and they may provide multiple paths, comma separated.
```Batchfile
php artisan blueprint:trace --path="vendor\spatie\laravel-permission\src\Models,packages\my-package\src\Models"
Traced 7 models
```
The `appClasses` function now loads the file content to get its namespace, previously it was using the path of the working folder (for instance, `app` or `app\Models`) and the filename, to infer `App\Models\User`. 
Since now we can load files from other paths, like …

Added path option to Trace command

---

src/Generators/Statements/ResourceGenerator.php
tests/Feature/Generators/Statements/ResourceGeneratorTest.php
tests/fixtures/drafts/resource-nested.yaml
tests/fixtures/resources/certificate-with-nested-resource.php

Hello,
I have added nested resources when use resource:api.
What do you think about it? 
Good day,
Yannik

ADDED - nested resources

---

src/Tracer.php
tests/Feature/Commands/TraceCommandTest.php
tests/TestCase.php

This is a fix to #490.
This makes `relativeClassName` return the classname relative to models namespace.
The tests are ok, as far as I know this is only used to generate relationships of new entries, and that is working too.
This function was a little bit nonsense, because it first checked if config was set, if so, return, otherwise it would return a string where it would try to replace/remove the config, but there the config was never set anyway. I believe this was introduced to overcome the issue that was fixed on #477.
---
Before this PR, with `'models_namespace' => 'Models'` config, `Trace` would generate the following `.blueprint`;
```yaml
models:
Models\Address: { street: 'string nullable', country: string, icon_id: 'integer nullable', monster_id: integer }
Models\Icon: { name: …
```

Make `relativeClassName` return class name relative to models namespace

---

src/Lexers/ModelLexer.php
tests/Feature/Lexers/ModelLexerTest.php
tests/fixtures/drafts/post.yaml
tests/fixtures/factories/post-configured-laravel8.php
tests/fixtures/factories/post-configured.php
tests/fixtures/factories/post-laravel8.php
tests/fixtures/factories/post.php

Since [v8.36.0](https://github.com/laravel/framework/blob/b09394ed478551d01f5a6ce3111e4d140041bc82/CHANGELOG-8.x.md#v8360-2021-04-06), Laravel supports the `useCurrentOnUpdate` modifier – https://github.com/laravel/framework/pull/36817
This PR adds it to the list of `$modifiers`.

Added support for `useCurrentOnUpdate` modifier

---

README.md

There was one missed spot where it was said that Laravel 6 is still supported. Wanted to fix that.

Update README to reflect new support policy

---

src/Tracer.php
tests/Feature/Commands/TraceCommandTest.php
tests/TestCase.php

Hi @jasonmccreary!
My last PR (https://github.com/laravel-shift/blueprint/pull/488) introduced a possible problem on Trace command, so I'm here to fix it!
We found that non valid files, like a `.zip` file, breaks the Trace command, it generates an empty entry with a backslash (`"\"`), and `class_exists` breaks with that string.
It's a rare situation, but when it happens developers have no feedback about it.
This PR fixes it.

Fix Trace command when non valid files are found

---

src/Generators/MigrationGenerator.php

Was already removing the Laravel 7 checks in the MigrationGenerator. Once this is merged I will fix conflicts in https://github.com/laravel-shift/blueprint/pull/502.

Remove Laravel 7 or newer checks.

---

src/Generators/MigrationGenerator.php
tests/fixtures/migrations/model-key-constraints.php
tests/fixtures/migrations/uuid-shorthand-constraint.php

This pull request will change
```php
$table->uuid('sub_id');
$table->foreign('sub_id')->references('id')->on('subscriptions');
```
with the Laravel 8 `foreignUuid` method
```php
$table->foreignUuid('sub_id')->constrained('subscriptions');
```

Add foreignUuid method to replace uuid() and foreign()

---

src/Generators/MigrationGenerator.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Models/Attachment.php
tests/fixtures/drafts/foreign-with-class.yaml
tests/fixtures/migrations/foreign-with-class.php

This syntax is currently generating a wrong migration
```yaml
models:
Event:
working_title: string
image_id: uuid foreign:\Foo\Bar\Attachment
```
```php
$table->foreign('image_id')->references('id')->on('\Foo\Bar\Attachments');
```
This makes that inserting record in mysql will fail, since `\Foo\Bar\Attachments` is not an existing table.
The changes in this pull request will fix this.
New output will be 
```php
$table->foreignUuid('image_id')->constrained('attachments');
```

If $on is a class, we will try to fetch the table from that class

---

src/Generators/ModelGenerator.php
tests/fixtures/models/alias-relationships.php
tests/fixtures/models/certificate-pascal-case-example.php
tests/fixtures/models/certificate-type-pascal-case-example.php
tests/fixtures/models/custom-pivot-table-name.php
tests/fixtures/models/foreign-key-shorthand-phpdoc.php
tests/fixtures/models/model-configured.php
tests/fixtures/models/model-relationships-morphone-morphmany-with-fqn.php
tests/fixtures/models/model-relationships-with-full-namespace.php
tests/fixtures/models/model-relationships.php
tests/fixtures/models/nested-models.php
tests/fixtures/models/post-polymorphic-relationship.php
tests/fixtures/models/readme-example-phpdoc.php
tests/fixtures/models/readme-example.php
tests/fixtures/models/relationships-phpdoc.php
tests/fixtures/models/relationships.php
tests/fixtures/models/return-type-declarations.php
tests/fixtures/models/soft-deletes-phpdoc.php
tests/fixtures/models/soft-deletes.php
tests/fixtures/models/unconventional.php
tests/fixtures/models/user-polymorphic-relationship.php

(for models in same namespace)

Resolves #484 - Do not use FQCN for model relationships 

---

src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
src/Lexers/ModelLexer.php
src/Models/Model.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/fixtures/drafts/many-to-many-polymorphic-relationships.yaml
tests/fixtures/drafts/morphed-by-many.yaml
tests/fixtures/migrations/morphed-by-many-intermediate.php
tests/fixtures/migrations/morphed-by-many.php
tests/fixtures/models/post-many-to-many-polymorphic-relationship.php
tests/fixtures/models/tag-many-to-many-polymorphic-relationship.php
tests/fixtures/models/video-many-to-many-polymorphic-relationship.php

Adds the missing relationships and the relevant intermediate table. Follows the convention of singular table name + 'able'.

Resolves #482 Many to Many Polymorphic

---

src/BlueprintServiceProvider.php
src/Commands/NewCommand.php
src/Commands/PublishStubsCommand.php

…and add some shortcut flags to the blueprint:new command for streamline publishing - Closes #528

Add new command to publish stubs

---

src/Commands/BuildCommand.php
src/Generators/Statements/ViewGenerator.php
tests/Feature/Generators/Statements/ViewGeneratorTest.php

Hello,
This update will print the list of the skipped views while executing `blueprint:build` command. This PR implements the TODO comment in `ViewGenerator:41`.
Before the update:
After the update:

Improvement: show skipped views in the output of build command

---

tests/Feature/Generators/FactoryGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/Feature/Generators/SeederGeneratorTest.php

Given the package is now php 8.0.0 and higher. Also, those alternate stubs no longer exist

chore: remove old version compare code

---

src/Generators/AbstractClassGenerator.php

This pull request closes #479 by having the $tree variable as a protected property instead of a private property as he requested. It does then keep it inline with the other variables in the abstract method.

Update $tree visibility from private to protected. Closes #479

---

src/Generators/TestGenerator.php
tests/Feature/Generators/TestGeneratorTest.php
tests/fixtures/drafts/controllers-only-no-context.yaml
tests/fixtures/tests/controllers-only-no-context.php

Fixes #549 
Note that the expected test output would fail as we have no context for `$auth` or `$event`.

Fix exception for variables without context

---

src/Generators/Statements/MailGenerator.php
src/Lexers/StatementLexer.php
src/Models/Statements/SendStatement.php
stubs/mail.stub
stubs/mail.view.stub
tests/Feature/Generators/Statements/MailGeneratorTest.php
tests/Feature/Lexers/StatementLexerTest.php
tests/fixtures/drafts/send-statement-with-view.yaml
tests/fixtures/mailables/added-admin-view.blade.php
tests/fixtures/mailables/added-admin.php
tests/fixtures/mailables/mail-configured.php
tests/fixtures/mailables/published-post-view.blade.php
tests/fixtures/mailables/published-post.php
tests/fixtures/mailables/return-type-declarations.php
tests/fixtures/mailables/review-post-view.blade.php

This updates Blueprint to generate an empty Blade template for any generated Mailable. By default, the kebab case of the Mailable name is used and stored under the `resources/views/emails` folder. You may customize the template name (and path) by passing an optional `view` argument to the `send` statement.
Example:
```yaml
send: ReviewPost to:post.author with:foo, bar, baz view:emails.posts.review
```
Note: This also contains a change to the `SendStatement` constructor to add the new argument as well as fix a PHP 8 warning about the order of optional arguments.
---
Closes #506

Generate mail views

---

src/Translators/Rules.php
tests/Feature/Translators/RulesTest.php
tests/fixtures/form-requests/certificate-store.php
tests/fixtures/form-requests/certificate-update.php

Currently, Blueprint does not explicitly set the `nullable` validation rule for `nullable` columns. This means the generated form request requires `nullable` columns to be set or not in the request data at all.
For example, a `published_at` date column which is nullable would generate the validation rule `['date']`. As such, attempting to set this `published_at` column to `null` would cause validation to fail. That is not the expected behavior for a nullable column.
Originally, the thought was the columns you passed to a `validate` statement should all be "required". While that is the common case, it's assuming (too fancy).
I now think adding the `nullable` validation rule to database columns which are `nullable` generates an expected set of ready-to-use validation rules. If the developer …

Explicitly set nullable validation rule

---

src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
src/Lexers/ModelLexer.php
src/Models/Model.php
stubs/model.incrementing.stub
stubs/model.table.stub
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/fixtures/drafts/custom-pivot.yaml
tests/fixtures/drafts/model-with-meta.yaml
tests/fixtures/migrations/custom_pivot_team_user_table.php
tests/fixtures/migrations/custom_pivot_teams_table.php
tests/fixtures/migrations/custom_pivot_users_table.php
tests/fixtures/migrations/model-with-meta.php
tests/fixtures/models/custom-pivot-membership.php
tests/fixtures/models/custom-pivot-team.php
tests/fixtures/models/custom-pivot-user.php
tests/fixtures/models/model-with-meta.php

This PR adds basic support for a `meta` key to be defined on models. If the `meta` value is a string, it will continue to be used as a column definition. When it is an array, it will be used as additional configuration to customize the model.
Currently, supported keys are `pivot` and `table` to create a [pivot model](https://laravel.com/docs/9.x/eloquent-relationships#defining-custom-intermediate-table-models) and customize the table name, respectively.
For example:
```yaml
models:
Membership:
meta:
pivot: true
table: team_user
user_id: id
team_id: id
```
This lays the foundation to support other customizations, such as class inheritance, controller middleware, authorization policies, etc.
---
Closes #305 and #328

Introduce `meta` key for customizations

---

src/Generators/ControllerGenerator.php
tests/Feature/BlueprintTest.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/Feature/Generators/FactoryGeneratorTest.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/Feature/Generators/RouteGeneratorTest.php
tests/Feature/Generators/Statements/NotificationGeneratorTest.php
tests/Feature/Generators/TestGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/Feature/Lexers/StatementLexerTest.php
tests/Feature/Translators/RulesTest.php
tests/Unit/EnumTypeTest.php
tests/fixtures/controllers/controller-returns-view-typehint.php
tests/fixtures/controllers/return-type-declarations.php
tests/fixtures/drafts/controller-returns-view-typehint.yaml

Return correct return-type hints

---

src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Generators/Statements/FormRequestGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/fixtures/drafts/form-requests-softdeletes.yaml
tests/fixtures/drafts/form-requests-softdeletestz.yaml
tests/fixtures/form-requests/form-requests-softdeletes.php
tests/fixtures/form-requests/form-requests-softdeletestz.php
tests/fixtures/migrations/soft-deletes-respect-order.php
tests/fixtures/migrations/soft-deletes.php
tests/fixtures/migrations/with-path-prefix-table-name-region.php
tests/fixtures/migrations/with-timezones.php
tests/fixtures/models/soft-deletes-phpdoc.php

Remove superfluous `softDeletes` & `softDeletesTz` columns

---

phpunit.xml

Resolves the deprecation warning of the configuration.
```
There was 1 PHPUnit test runner deprecation:
1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
OK, but there are issues!
Tests: 382, Assertions: 1846, Deprecations: 1.
```

Migrate PHPUnit XML configuration using "--migrate-configuration"

---

src/Generators/ControllerGenerator.php
src/Generators/Statements/EventGenerator.php
src/Generators/Statements/JobGenerator.php
src/Generators/Statements/MailGenerator.php
src/Generators/Statements/NotificationGenerator.php
src/Generators/TestGenerator.php

> Extracted from https://github.com/laravel-shift/blueprint/pull/612 to keep the PRs easier to digest and this is more of a prerequisite for the mentioned PR rather than a part of it. 
This PR makes it possible to handle statements where the value is an array, as will be the case after merging the above mentioned PR.

Add support for iterating over statement children

---

src/Generators/ModelGenerator.php
src/Generators/Statements/ResourceGenerator.php
src/Tree.php
tests/Unit/TreeTest.php

> Resolves https://github.com/laravel-shift/blueprint/issues/340
Currently it only throws in two places, based on the cases I could track down where `modelForContext` is called and afterwards a `Model` instance is expected or unhandled exceptions will be encountered.

Throw an exception when a required model is missing

---

src/Blueprint.php
src/Generators/ControllerGenerator.php
src/Generators/Statements/EventGenerator.php
src/Generators/Statements/JobGenerator.php
src/Generators/Statements/MailGenerator.php
src/Generators/Statements/NotificationGenerator.php
src/Generators/TestGenerator.php
src/Lexers/StatementLexer.php
tests/Feature/BlueprintTest.php
tests/fixtures/drafts/multiple-dispatch-fire-notify-send-keys.yaml

> Alternative to https://github.com/laravel-shift/blueprint/pull/612 for https://github.com/laravel-shift/blueprint/issues/611
This new approach preprocesses the YAML content and transforms duplicate keys into keys that are suffixed with their line number to avoid key collisions. This also reverts https://github.com/laravel-shift/blueprint/pull/619.
**Input**
https://github.com/laravel-shift/blueprint/pull/623/files#diff-a4f4e06b3fdb4a8424880f544fca3c75a0ecf2ebb5158feba4963f7066e2d265
**Output**
https://github.com/laravel-shift/blueprint/pull/623/files#diff-72d9e08bf23239b5487ea8767fe78e8f3e9be1b14e5bd64e1ae2c4848da167f1

Allow multiple dispatch, fire, notify and send statements

---

src/Generators/MigrationGenerator.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/fixtures/drafts/omits-length-for-integers.yaml
tests/fixtures/migrations/omits-length-for-integers.php

Resolves https://github.com/laravel-shift/blueprint/issues/572

Omit length for integer values in migrations

---

src/Generators/PhpUnitTestGenerator.php
stubs/phpunit.test.case.stub
stubs/phpunit.test.class.stub
tests/Feature/Commands/BuildCommandTest.php
tests/Feature/Commands/EraseCommandTest.php
tests/Feature/Commands/InitCommandTest.php
tests/Feature/Commands/NewCommandTest.php
tests/Feature/Commands/TraceCommandTest.php
tests/Unit/EnumTypeTest.php
tests/Unit/TreeTest.php
tests/fixtures/tests/phpunit/api-shorthand-validation.php
tests/fixtures/tests/phpunit/call-to-a-member-function-columns-on-null-Api-PaymentControllerTest.php
tests/fixtures/tests/phpunit/call-to-a-member-function-columns-on-null-PaymentControllerTest.php
tests/fixtures/tests/phpunit/call-to-a-member-function-columns-on-null-SubscriptionControllerTest.php
tests/fixtures/tests/phpunit/call-to-a-member-function-columns-on-null-TelegramControllerTest.php
tests/fixtures/tests/phpunit/certificate-pascal-case-example.php
tests/fixtures/tests/phpunit/certificate-type-pascal-case-example.php
tests/fixtures/tests/phpunit/controllers-only-no-context.php
tests/fixtures/tests/phpunit/crud-show-only.php
tests/fixtures/tests/phpunit/full-crud-example.php
tests/fixtures/tests/phpunit/models-with-custom-namespace.php
tests/fixtures/tests/phpunit/readme-example-notification.php
tests/fixtures/tests/phpunit/readme-example.php
tests/fixtures/tests/phpunit/reference-cache.php
tests/fixtures/tests/phpunit/respond-statements.php
tests/fixtures/tests/phpunit/routes-with-pluralized-names.php

Resolves https://github.com/laravel-shift/blueprint/issues/629

Use attributes for PHPUnit 10 tests

---

src/Generators/ModelGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/Feature/Generators/Statements/ResourceGeneratorTest.php
tests/Feature/Lexers/ModelLexerTest.php
tests/fixtures/drafts/alias-relationships.yaml
tests/fixtures/drafts/infer-belongsto.yaml
tests/fixtures/migrations/infer-belongsto.php
tests/fixtures/migrations/models-with-custom-namespace.php
tests/fixtures/models/infer-belongsto.php
tests/fixtures/resources/certificate-with-nested-resource.php

After watching Blueprint in action on a [Laracast Series](https://laracasts.com/series/rapid-laravel-development-with-filament/episodes/1), I realized a use case that could be optimized. Blueprint is all about conventions and rapid development, but this video demonstrated some confusion on when to define model `columns` as well as `relationships`. Particularly in the case of `belongsTo`.
Consider the following draft file:
```yaml
models:
Conference:
name: string
venue_id: unsigned bigInteger
relationships:
belongsTo: Venue, Region
```
In this case a user has defined what they believe to be a foreign key column, but also the `belongsTo` relationship to `Venue`. While there are a few ways you may write this, ideally you would do one or the other. Personally, I would not define a `belongsTo` …

Infer `belongsTo` relationships

---

src/Generators/MigrationGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Lexers/ModelLexerTest.php
tests/fixtures/migrations/belongs-to-many.php
tests/fixtures/migrations/identity-columns-big-increments.php
tests/fixtures/migrations/identity-columns.php
tests/fixtures/migrations/indexes.php
tests/fixtures/migrations/infer-belongsto.php
tests/fixtures/migrations/models-with-custom-namespace.php
tests/fixtures/migrations/readme-example.php
tests/fixtures/migrations/relationships.php
tests/fixtures/migrations/soft-deletes.php
tests/fixtures/migrations/unconventional.php

It seems recent code uses `foreignId` when setting the column data type for many and polymorphic relationship foreign keys. However, the standard `belongsTo` relationship still uses `unsignedBigInteger` as the data type. For consistency within Blueprint and to align with whatever data type Laravel uses for "id" columns `foreignId` is now used.
Given the following draft file:
```yaml
models:
Post:
author_id: id
```
**Before:**
```php
Schema::create('posts', function (Blueprint $table) {
$table->unsignedBigInteger('author_id');
}
```
**After:**
```php
Schema::create('posts', function (Blueprint $table) {
$table->foreignId('author_id');
}
```

Use `foreignId` for consistency

---

.gitignore
src/Generators/ModelGenerator.php
src/Models/Model.php
tests/Feature/Generators/ModelGeneratorTest.php

Add HasUuids trait when Model has id uuid primary. 

---

config/blueprint.php
src/Generators/MigrationGenerator.php
src/Generators/RouteGenerator.php
tests/Feature/Generators/RouteGeneratorTest.php
tests/fixtures/routes/api-routes-plural.php
tests/fixtures/routes/api-routes-singular.php
tests/fixtures/routes/api-routes.php
tests/fixtures/routes/cruddy.php
tests/fixtures/routes/invokable-controller.php
tests/fixtures/routes/multiple-resource-controllers-api.php
tests/fixtures/routes/multiple-resource-controllers-web.php
tests/fixtures/routes/non-cruddy.php
tests/fixtures/routes/readme-example-plural.php
tests/fixtures/routes/readme-example-singular.php
tests/fixtures/routes/readme-example.php
tests/fixtures/routes/respond-statements.php
tests/fixtures/routes/routes-mixed.php

This uses the plural of a modal for resource controllers by default to match the examples in the Laravel docs as discussed in #662 . Singular still remains possible via a config setting.
I checked the docs and could not find any references to the singular ones, so no need for changes there as far as I could see.

Plural routes by default

---

composer.json
src/Tracer.php

Remove DBAL for Laravel 11: Fix type mappings

---

src/Generators/PestTestGenerator.php
src/Generators/PhpUnitTestGenerator.php
src/Models/Column.php
src/Models/Model.php
tests/Feature/Generators/PestTestGeneratorTest.php
tests/Feature/Generators/PhpUnitTestGeneratorTest.php
tests/fixtures/drafts/date-formats.yaml
tests/fixtures/tests/pest/api-shorthand-validation.php
tests/fixtures/tests/pest/certificate-pascal-case-example.php
tests/fixtures/tests/pest/date-formats.php
tests/fixtures/tests/phpunit/api-shorthand-validation.php
tests/fixtures/tests/phpunit/certificate-pascal-case-example.php
tests/fixtures/tests/phpunit/date-formats.php

Currently, Blueprint uses Faker dates for columns with a _date_ data type. This either generates you a `string` or a `DateTimeInterface` object. Neither of these are readily useable for testing.
This PR parses the returned faker data into an `Illuminate\Support\Carbon` object. This allows it to be used more readily in tests.

Parse fake dates into Carbon objects

---

src/Generators/MigrationGenerator.php
src/Generators/ModelGenerator.php
src/Lexers/ModelLexer.php
src/Models/Model.php
stubs/model.connection.stub
tests/Feature/Generators/MigrationGeneratorTest.php
tests/Feature/Generators/ModelGeneratorTest.php
tests/fixtures/drafts/model-with-meta.yaml
tests/fixtures/migrations/model-with-meta.php
tests/fixtures/models/model-with-meta.php

This adds a `connection` option to the `meta` section of a model, which will generate a model and any migration with the `$connection` property set to that value.
For example:
```yaml
models:
Example:
meta:
connection: readonly
```
---
Closes #639

Ability to set model connection

---

src/Models/Statements/RenderStatement.php
tests/fixtures/components/properties-statements.php
tests/fixtures/controllers/controller-configured.php
tests/fixtures/controllers/crazy-eloquent.php
tests/fixtures/controllers/nested-components.php
tests/fixtures/controllers/readme-example-notification-facade.php
tests/fixtures/controllers/readme-example-notification-model.php
tests/fixtures/controllers/readme-example.php
tests/fixtures/controllers/with-all-policies.php
tests/fixtures/controllers/with-authorize-resource.php
tests/fixtures/controllers/with-some-policies.php

Blueprint used `compact` when generating code to pass `view` data. This was really for ease of output and not necessarily convention. In fact, when it comes to view data, Laravel has no documented examples using `compact`. So its use is really just a legacy convention likely from the broader PHP community.
Splitting this out into the full array allows this statement to do more. For example, inline statements or support new code generation for Livewire.

Modernize view data syntax

---

src/Generators/MigrationGenerator.php
src/Lexers/ModelLexer.php
tests/Feature/Generators/MigrationGeneratorTest.php
tests/fixtures/drafts/geometry-columns.yaml
tests/fixtures/migrations/geometry-columns.php

This adds support to properly generate the migrations using `geometry` and `geography` types in Laravel 11 applications.
```yaml
models:
Example:
coordinates: geography:point,4326
positions: geometry:point,0
```
**Note**: while Blueprint will generate code using these types for a Laravel 10 application Laravel may no recognize them. You should use the [old data types](https://laravel.com/docs/10.x/migrations#available-column-types) in your Laravel 10 applications.

Output new Laravel 11 geo column types

---

src/Generators/ControllerGenerator.php
src/Lexers/StatementLexer.php
src/Models/Statements/InertiaStatement.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/Feature/Lexers/StatementLexerTest.php
tests/fixtures/controllers/inertia-render.php
tests/fixtures/drafts/inertia-render.yaml

As Blueprint now generates Livewire components, it seemed fitting to introduce at least something for Inertia. This adds a new `inertia` controller statement to render a page with data.
```yaml
controllers:
Event:
show:
inertia: example.page with:event
```
Generates:
```php
use Inertia\Inertia;
use Inertia\Response;
class EventController extends Controller
{
public function show(Event $event): Response
{
return Inertia::render('Event/Show', [
'event' => $event,
]);
// ...
}
```

Support new `inertia` controller statement

---

src/Generators/ControllerGenerator.php
tests/fixtures/controllers/with-all-policies.php
tests/fixtures/controllers/with-some-policies.php

Laravel 11 has marked the "base controller" as `abstract` and no longer includes the previous traits. As such, methods like `middleware`, 'validate`, `authorize`, etc are no longer available.
Currently, Blueprint only uses `authorize` and `authorizeResource` methods. This PR updates the former to use the `Gate` facade directly to avoid errors in Laravel 11 (#701).
**Note**: There does not seem to be an equivalent for `authorizeResource` on `Gate`. For now, this is left as `$this->authorizeResource` for compatibility with Laravel 10. If you require this method in a Laravel 11 app, you may import the `AuthorizeResource` trait in your controller. However, this trait and method do not appear to be use within Laravel and may be removed in future versions of Laravel and Blueprint.

Use `Gate` facade directly

---

src/Generators/ControllerGenerator.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/fixtures/controllers/inertia-render.php
tests/fixtures/controllers/with-all-policies.php
tests/fixtures/controllers/with-authorize-resource.php
tests/fixtures/controllers/with-some-policies.php
tests/fixtures/drafts/controller-configured.yaml

There were a few areas where the configured `model_namespace` was not being respected when Blueprint "guessed" model references. This corrects that bug fixing #702.

Respect model namespace when guessing

---

tests/Feature/Lexers/StatementLexerTest.php
tests/fixtures/controllers/inertia-render.php
tests/fixtures/drafts/inertia-render.yaml

When I'm going through a project, I like to read the tests as a form of documentation.  This PR updates the tests that were created for the new Inertia support to follow the Inertia naming convention to make it clearer how to use the new feature in that specific context.

Update new Inertia tests to follow naming convention

---

src/Translators/Rules.php
tests/Feature/Translators/RulesTest.php

On a clean installation, a foreign key column specifying the name of the related table generates an incorrect `exists` rule in the form request. For instance, the following YAML:
```yaml
models:
Message:
subject: string
sender_id: id foreign:users
controllers:
Message:
resource: api
```
... generates these rules in `MessageStoreRequest` and `MessageUpdateRequest`:
```php
public function rules(): array
{
return [
'subject' => ['required', 'string'],
'sender_id' => ['required', 'integer', 'exists:senders,id'],
];
}
```
The expected rule for `sender_id` should be:
```diff
-'sender_id' => ['required', 'integer', 'exists:senders,id'],
+'sender_id' => ['required', 'integer', 'exists:users,id'],
```
This PR updates the `Rules` translator to verify if the column includes a foreign table modifier …

Fix `exists` rule for foreign key column indicating table name

---

config/blueprint.php
src/Generators/ControllerGenerator.php
src/Generators/Statements/ResourceGenerator.php
src/Models/Statements/ResourceStatement.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/Feature/Generators/Statements/ResourceGeneratorTest.php
tests/Feature/Lexers/StatementLexerTest.php
tests/TestCase.php
tests/fixtures/controllers/without-generating-resource-collection-classes.php

This PR introduces a new configuration option, `generate_resource_collection_classes`, to toggle the generation of resource collection classes in Blueprint.
To return a resource collection, Blueprint creates a **resource collection class**. These classes allows adding custom metadata that may need to be returned with the collection.
```php
class PostCollection extends ResourceCollection
{
public function toArray(Request $request): array
{
return [
'data' => $this->collection,
];
}
}
```
Blueprint uses them in controllers using the `resource` statement, generating code like this:
```php
use App\Http\Resources\PostCollection;
use App\Http\Resources\PostResource;
public function index(Request $request): PostCollection
{
$posts = Post::paginate();
return new PostCollection($posts);
}
public …
```

Add option to disable generation of resource collection classes

---

src/Generators/PestTestGenerator.php
tests/fixtures/tests/pest/api-shorthand-validation.php
tests/fixtures/tests/pest/call-to-a-member-function-columns-on-null-Api-PaymentControllerTest.php
tests/fixtures/tests/pest/call-to-a-member-function-columns-on-null-PaymentControllerTest.php
tests/fixtures/tests/pest/certificate-pascal-case-example.php
tests/fixtures/tests/pest/certificate-type-pascal-case-example.php
tests/fixtures/tests/pest/date-formats.php
tests/fixtures/tests/pest/full-crud-example.php
tests/fixtures/tests/pest/models-with-custom-namespace.php
tests/fixtures/tests/pest/readme-example-notification.php
tests/fixtures/tests/pest/readme-example.php
tests/fixtures/tests/pest/reference-cache.php
tests/fixtures/tests/pest/respond-statements.php
tests/fixtures/tests/pest/routes-with-pluralized-names.php
tests/fixtures/tests/pest/routes-with-singular-names.php

On a clean installation, the generated Pest tests fail because `assertActionUsesFormRequest` is an undefined method.
Installation:
```sh
composer create-project laravel/laravel test
cd test
composer require -W --dev laravel-shift/blueprint
composer remove phpunit/phpunit
composer require pestphp/pest --dev --with-all-dependencies
composer require pestphp/pest-plugin-faker --dev
composer require pestphp/pest-plugin-laravel --dev
./vendor/bin/pest --init
composer require --dev jasonmccreary/laravel-test-assertions
```
Initialize Blueprint:
```sh
php artisan blueprint:new --config
```
Comment out PHPUnit and uncomment Pest:
```php
// 'test' => \Blueprint\Generators\PhpUnitTestGenerator::class,
'test' => \Blueprint\Generators\PestTestGenerator::class,
```
Create draft:
```yaml
models:
Post: …
```

Fix Pest generated tests

---

src/Generators/PestTestGenerator.php

This is a complementary PR for https://github.com/laravel-shift/blueprint/pull/726 that updates the `PestTestGenerator` to use the `HandlesTraits` trait and override only the `buildTraits` method.

Make PestTestGenerator use HandlesTraits trait

---

src/Generators/ControllerGenerator.php
src/Generators/PestTestGenerator.php
src/Generators/PhpUnitTestGenerator.php
src/Generators/RouteGenerator.php
src/Lexers/ControllerLexer.php
src/Models/Controller.php
tests/Feature/Generators/ControllerGeneratorTest.php
tests/Feature/Generators/PestTestGeneratorTest.php
tests/Feature/Generators/PhpUnitTestGeneratorTest.php
tests/Feature/Generators/RouteGeneratorTest.php
tests/Feature/Lexers/ControllerLexerTest.php
tests/fixtures/controllers/api-resource-nested.php
tests/fixtures/drafts/api-resource-nested.yaml
tests/fixtures/drafts/controller-nested.yaml
tests/fixtures/routes/nested-controller.php
tests/fixtures/tests/pest/api-resource-nested.php
tests/fixtures/tests/phpunit/api-resource-nested.php

This PR introduces support for defining routes with nested model bindings by specifying a `meta.parent` attribute in the controller's configuration. The `parent` attribute identifies the name of the related model.
Given the following draft:
```yaml
controllers:
Comment:
resource: api
meta:
parent: post
```
Blueprint will generate a **nested resource route** instead of a standard resource route:
```diff
-Route::apiResource('comments', App\Http\Controllers\CommentController::class);
+Route::apiResource('posts/{post}/comments', App\Http\Controllers\CommentController::class);
```
The `meta.parent` works not only for web or API resources, but for individual routes as well:
```php
Route::get('posts/{post}/comments/foobar', [App\Http\Controllers\CommentController::class, 'foobar']);
```
The …

Add support for routes with nested model binding

---

tests/fixtures/tests/pest/api-resource-nested.php

This PR fixes a test that fails due to the changes introduced by https://github.com/laravel-shift/blueprint/pull/725.

Fix failing resource nested test

---

src/Generators/RouteGenerator.php
stubs/routes.api.stub
tests/Feature/Generators/RouteGeneratorTest.php

In a clean installation of Laravel 11, the `routes/api.php` file is absent and not configured in `bootstrap/app.php`. When Blueprint generates API routes, it creates the file, but the developer must manually edit it to add the PHP opening tag and the `use Illuminate\Support\Facades\Route;` line. They must also modify `bootstrap/app.php` to enable that API route file.
This PR updates Blueprint to check the following when creating API routes:
- Ensure the `routes/api.php` file exists, creating it if necessary, using a [basic stub](https://github.com/nicodevs/blueprint/blob/setup-api-routes/stubs/routes.api.stub)
- Ensure the API routes file is configured in `bootstrap/app.php`, adding the configuration if missing
These actions occur before the addition of the generated API routes.
This PR …

Set up API router when first API routes are generated

---

src/Generators/RouteGenerator.php
tests/Feature/Generators/RouteGeneratorTest.php

This PR fixes a logical error introduced in https://github.com/laravel-shift/blueprint/pull/728, where `configureApiRoutesInAppBootstrap` was always called instead of only when the `routes/api.php` file is missing.

Fix: Write bootstrap file only when routes API file is missing

---

tests/Feature/Generators/RouteGeneratorTest.php

This PR streamlines a test introduced in https://github.com/laravel-shift/blueprint/pull/728. [Related comment](https://github.com/laravel-shift/blueprint/pull/728#discussion_r1902256742)

Simplify the test verifying the uncommenting of the API route line in the app bootstrap file

---

src/Generators/Statements/FormRequestGenerator.php
tests/Feature/Generators/Statements/FormRequestGeneratorTest.php
tests/fixtures/drafts/form-requests-controller-has-parent.yaml
tests/fixtures/form-requests/form-requests-controller-has-parent.php

Since https://github.com/laravel-shift/blueprint/pull/725, we can use `meta.parent` to generate routes with nested model binding. For example, this draft:
```yaml
controllers:
Comment:
resource: api
meta:
parent: post
```
... generates the following routes:
```
GET|HEAD        api/posts/{post}/comments
POST            api/posts/{post}/comments
GET|HEAD        api/posts/{post}/comments/{comment}
PUT|PATCH       api/posts/{post}/comments/{comment}
DELETE          api/posts/{post}/comments/{comment}
```
Laravel automatically resolves the Post model matching the provided `{post}` ID or returns a 404 if not found. For this reason, receiving and validating `post_id` in the `FormRequest` for these routes is redundant.
This PR removes the generation of form requests validation rules for columns …

Omit redundant parent ID validation

---

src/Generators/PestTestGenerator.php
tests/Feature/Generators/PestTestGeneratorTest.php
tests/fixtures/tests/pest/api-resource-nested.php
tests/fixtures/tests/pest/api-shorthand-validation.php
tests/fixtures/tests/pest/call-to-a-member-function-columns-on-null-Api-PaymentControllerTest.php
tests/fixtures/tests/pest/call-to-a-member-function-columns-on-null-PaymentControllerTest.php
tests/fixtures/tests/pest/certificate-pascal-case-example.php
tests/fixtures/tests/pest/certificate-type-pascal-case-example.php
tests/fixtures/tests/pest/date-formats.php
tests/fixtures/tests/pest/full-crud-example.php
tests/fixtures/tests/pest/models-with-custom-namespace.php
tests/fixtures/tests/pest/readme-example-notification.php
tests/fixtures/tests/pest/readme-example.php
tests/fixtures/tests/pest/reference-cache.php
tests/fixtures/tests/pest/respond-statements.php
tests/fixtures/tests/pest/routes-with-pluralized-names.php
tests/fixtures/tests/pest/routes-with-singular-names.php
tests/fixtures/tests/pest/test-case-with-additional-assertions.php
tests/fixtures/tests/pest/test-case.php

This PR modifies the strategy for importing `AdditionalAssertions` into Pest tests, changing from importing it in every test to importing it once in `test/TestCase.php` (from which Pest tests extend). The original idea was not to alter files beyond those generated, but doing so avoids boilerplate and streamlines the codebase. Check https://github.com/laravel-shift/blueprint/pull/726#issuecomment-2568598874
If validation statements are detected, `PestTestGenerator` checks if the file `test/TestCase.php` exists. If it does, it verifies whether `AdditionalAssertions` is imported. If not, the following modifications are made:
```diff
<?php
namespace Tests;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
+use JMac\Testing\Traits\AdditionalAssertions;
abstract class TestCase extends …
```

Import AdditionalAssertions to base test case when generating Pest tests

---

config/blueprint.php
src/Generators/Statements/InertiaPageGenerator.php
stubs/inertia.react.stub
stubs/inertia.svelte.stub
stubs/inertia.vue.stub
tests/Feature/Generators/Statements/InertiaPageGeneratorTest.php
tests/fixtures/inertia-pages/customer-show.jsx
tests/fixtures/inertia-pages/customer-show.svelte
tests/fixtures/inertia-pages/customer-show.vue

Given the introduction of the `inertia` statement to indicate that the controller should return `Inertia::render`, it would be great if Blueprint could generate Inertia page components for the appropriate adapter (Vue, React, Svelte), similar to how the `render` statement triggers the generation of Blade templates.
This PR implements that feature by introducing an `InertiaPageGenerator`.
- It determines the adapter (Vue, React, Svelte) by reading the dependencies listed in `package.json`.
- If no adapter is found, it will not generate page components.
- If an adapter is detected, it iterates through the controller and statements, generating a page component using a stub appropriate for the adapter.
- It populates the stub with the statement data as props for the page component.
The stubs …

Inertia page generator

---

src/Generators/MigrationGenerator.php
tests/fixtures/drafts/unconventional-foreign-key.yaml
tests/fixtures/factories/unconventional-foreign-key.php
tests/fixtures/migrations/unconventional-foreign-key.php

This PR addresses a disconnect between the code and documentation in regards to customizing foreign keys.
The documentation stated:
> If you are not following Laravel's naming conventions, you may set the attribute on the `foreign` modifier. Blueprint supports either the foreign table name or the table and column name using dot notation.
The code always assumed the _table name_ was a model reference and either pluralized or snake cased the value.
After this PR, Blueprint either supports a _model reference_ (base class name or fully qualified class name) or the table and column name using dot notation.
Examples:
```yaml
country_id: id foreign:country          # table: countries column: id
ccid: string foreign:country.id         # table: country column: id
country_code: string …
```

Honor table name from dot notation

---

src/Lexers/ModelLexer.php

As caught by JMac on stream today, this adds "int" as a reference to "integer" in the Model Lexer since it's such a common way to reference integers that it acts as an intuitive guard rail

Add 'int' => 'integer' mapping in ModelLexer
