src/Generators/MigrationGenerator.php, tests/Feature/Generator/MigrationGeneratorTest.php, tests/fixtures/definitions/multiple-models.bp, tests/fixtures/migrations/comments.php, tests/fixtures/migrations/posts.php
=> Sequence migration timestamp by models

src/Generators/FactoryGenerator.php, src/Generators/MigrationGenerator.php, src/Generators/ModelGenerator.php, src/Lexers/ModelLexer.php
Added support for UUID data type for id columns.
Added support for `index` modifier.
Added support for `foreign` modifier - generates corresponding migration.
Added basic json column data type support.
=> Add uuid, json data types and index/foreign modifiers

src/Generators/ModelGenerator.php, tests/fixtures/definitions/nested-components.bp, tests/fixtures/factories/nested-components.php, tests/fixtures/models/nested-components.php
It's fillable with Laravel's default User.php model.
Closes #92
=> Include password field in fillable model properties

src/Generators/MigrationGenerator.php
No tests for this one yet, and maybe not a good looking implementation, but the output is right!
Closes #79 if merged. Feel free to continue work.
=> [WIP] Generate id() column on Laravel 7 and up

src/Generators/MigrationGenerator.php, tests/Feature/Lexers/ModelLexerTest.php, tests/fixtures/definitions/model-modifiers.bp, tests/fixtures/migrations/model-modifiers.php
=> fix: datatype of an `id` column

src/Generators/MigrationGenerator.php, src/Generators/ModelGenerator.php, src/Lexers/ModelLexer.php, src/Models/Model.php, tests/Feature/Lexers/ModelLexerTest.php, tests/fixtures/definitions/model-relationships.bp, tests/fixtures/models/model-relationships.php
Add tests to PR #104 
_I wasn't sure how to contribute to other user's pr. hopefully, this is okay._
=> support belongs to many relationship

src/Lexers/ModelLexer.php, tests/Feature/Lexers/ModelLexerTest.php
=> support space between quotes in `default` modifier

config/blueprint.php, src/Generators/FactoryGenerator.php, tests/Feature/Generator/FactoryGeneratorTest.php, tests/fixtures/factories/fake-nullables.php
=> add fake_nullable config

src/Generators/TestGenerator.php
Fixes destroy http method on generated tests.
Closes #142
=> Fix destroy http method

.github/workflows/continuous-integration.yml
Run `PHPUnit` test using:
```
php-version: [7.2, 7.3, 7.4]
laravel-version: [6, 7]
os: [ubuntu-latest, windows-latest, macos-latest]
```
=> feat: add continuous integration via github action

src/Commands/BlueprintCommand.php
Not the most eloquent solution but it should achieve the result you are looking for. 
---
Closes #157
=> Accept both draft.yaml and draft.yml file

src/Generators/FactoryGenerator.php
=> Changed "bigint" key from fakerDataType to "biginteger" 

src/Generators/ControllerGenerator.php, tests/Feature/Generator/ControllerGeneratorTest.php, tests/Feature/Generator/ModelGeneratorTest.php, tests/fixtures/controllers/custom-models-namespace.php, tests/fixtures/definitions/custom-models-namespace.bp, tests/fixtures/models/custom-models-namespace.php
=> fix: incorrect imports when using a custom namespace for models

src/Generators/RouteGenerator.php, src/Lexers/ControllerLexer.php, src/Models/Controller.php, tests/Feature/Generator/RouteGeneratorTest.php, tests/Feature/Lexers/ControllerLexerTest.php, tests/fixtures/definitions/api-routes-example.bp, tests/fixtures/routes/api-routes.php
This pull request makes api shorthand add routes to routes/api.php.
---
Closes #206
=> feat: api shorthand add routes to routes/api.php

src/Generators/MigrationGenerator.php, tests/Feature/Generator/MigrationGeneratorTest.php, tests/fixtures/definitions/nullable-chaining.bp, tests/fixtures/migrations/nullable-chaining-laravel6.php, tests/fixtures/migrations/nullable-chaining.php
This pull request fixes the invalid chaining of 'nullable' for 'foreignId'.
---
Closes #215
=> fix: invalid chaining of 'nullable' for 'foreignId'

src/Generators/Statements/FormRequestGenerator.php, src/Translators/Rules.php, tests/Feature/Generator/Statements/FormRequestGeneratorTest.php, tests/fixtures/definitions/model-reference-validate.bp, tests/fixtures/form-requests/certificate-store.php, tests/fixtures/form-requests/certificate-update.php
This pull request fixes no rules generated for belongs to relationship.
---
Closes #209
=> fix: no rules generated for belongs to relationship

.github/ISSUE_TEMPLATE/report-a-bug.md
As you mention in your current Livestream, all issues should include the `draft.yaml`.
=> Add draft.yaml section to bug template

src/Generators/FactoryGenerator.php, tests/Feature/Generator/FactoryGeneratorTest.php, tests/fixtures/definitions/unconventional-foreign-key.bp, tests/fixtures/factories/unconventional-foreign-key.php, tests/fixtures/migrations/unconventional-foreign-key.php
=> Generate proper fake relationship for model factory

src/Commands/TraceCommand.php
=> fix: jenssegers mongodb eloquent model class does not exist

src/Commands/BuildCommand.php
=> Fix typo in blueprint:build draft argument description

src/Generators/TestGenerator.php, tests/fixtures/tests/api-shorthand-validation.php, tests/fixtures/tests/certificate-pascal-case-example.php, tests/fixtures/tests/certificate-type-pascal-case-example.php, tests/fixtures/tests/models-with-custom-namespace.php
=> Generate assertions for Eloquent update statements

src/Generators/ControllerGenerator.php, src/Generators/FactoryGenerator.php, src/Generators/ModelGenerator.php, src/Generators/SeederGenerator.php, src/Generators/Statements/EventGenerator.php, src/Generators/Statements/FormRequestGenerator.php, src/Generators/Statements/JobGenerator.php, src/Generators/Statements/MailGenerator.php, src/Generators/Statements/ResourceGenerator.php, src/Generators/TestGenerator.php
This pull request make generator classes extendable.
---
Supercedes #296
Closes #293
=> Make generator classes extendable

src/Blueprint.php
After watching some live streams about blueprint. I fount it interesting to help refactor the project a bit.
I don't know if you would be interested to receive many small patches like this one or not. so please advice.
I will not add/modify functionalities, I will only refactor the code a bit to make code cleaner and more readable for new contributions, then I may contribute by adding new features as well.
I will submit another example PR so you can give me your thoughts and direction.
=> Refactor shouldGenerate using collection

src/Generators/SeederGenerator.php, src/Models/Statements/EloquentStatement.php, tests/Feature/Generator/ControllerGeneratorTest.php, tests/Unit/Models/Statements/EloquentStatementTest.php, tests/fixtures/controllers/certificate-controller.php, tests/fixtures/controllers/certificate-type-controller.php, tests/fixtures/controllers/controller-configured.php, tests/fixtures/controllers/custom-models-namespace.php, tests/fixtures/controllers/nested-components.php, tests/fixtures/controllers/readme-example-notification-facade.php, tests/fixtures/controllers/readme-example-notification-model.php, tests/fixtures/controllers/readme-example.php, tests/fixtures/controllers/save-without-validation.php, tests/fixtures/drafts/save-without-validation.yaml
=> Use $request->validated with validate statement

src/Lexers/ControllerLexer.php, tests/fixtures/controllers/certificate-controller.php, tests/fixtures/controllers/certificate-type-controller.php, tests/fixtures/controllers/custom-models-namespace.php, tests/fixtures/tests/api-shorthand-validation.php, tests/fixtures/tests/certificate-pascal-case-example.php, tests/fixtures/tests/certificate-type-pascal-case-example.php, tests/fixtures/tests/models-with-custom-namespace.php
=> Change api.destroy to return proper "no content"

src/Generators/Statements/ResourceGenerator.php, tests/Feature/Generator/ControllerGeneratorTest.php, tests/Feature/Generator/Statements/ResourceGeneratorTest.php, tests/fixtures/controllers/api-routes-example.php, tests/fixtures/drafts/api-routes-example.yaml, tests/fixtures/resources/certificate-collection.php, tests/fixtures/resources/certificate.php, tests/fixtures/routes/api-routes.php
=> Add support for namespaced JsonResources

src/Generators/Statements/FormRequestGenerator.php, tests/fixtures/form-requests/certificate-store.php, tests/fixtures/form-requests/certificate-update.php, tests/fixtures/form-requests/form-request-configured.php, tests/fixtures/form-requests/nested-components.php, tests/fixtures/form-requests/other-store.php, tests/fixtures/form-requests/post-index.php, tests/fixtures/form-requests/post-store.php, tests/fixtures/form-requests/reference-cache.php
=> Generate FormRequest rules using array syntax

src/Commands/BuildCommand.php
=> refactor: assign `-m` shortcut for `--overwrite-migrations` option

config/blueprint.php, src/Blueprint.php, src/BlueprintServiceProvider.php
- Swap the default generators or Add custom generators using the `config/blueprint.php` file.
resolves #313
=> feat: support custom generators via config

.github/workflows/build.yml
- Run the `Build` GitHub Action when you (@/jasonmccreary) push to master.
Currently, only pull requests are being tested.
=> Test on push via GitHub Action

.github/workflows/demo.yml
You can find it on this page [https://github.com/laravel-shift/blueprint/actions?query=workflow/Demo](https://github.com/laravel-shift/blueprint/actions?query=workflow%3ADemo) once it has been merged into the main branch of this repo.
- Setup Mysql
- Create a Laravel (6,7,8) app
- Link local repository (links to the pr)
- Install Blueprint
- Install laravel-test-assertions
- Run `php artisan blueprint:build` with `tests/fixtures/drafts/readme-example.yaml`
- Run `php artisan migrate:refresh`
- Run `php artisan test`
=> Build demo app via Github Actions

src/Generators/FactoryGenerator.php
=> fix: correct newline character for windows

src/Generators/MigrationGenerator.php, tests/Feature/Generators/MigrationGeneratorTest.php, tests/fixtures/drafts/boolean-column-default.yaml, tests/fixtures/migrations/boolean-column-default.php
Supersedes: #420
- Add test for [fixed issue with default for boolean type column (#420)](#420) from @iMokhles
close #420
=> Fix boolean column default modifier

src/Generators/ControllerGenerator.php, src/Generators/ModelGenerator.php, tests/Feature/Generators/ControllerGeneratorTest.php, tests/Feature/Generators/ModelGeneratorTest.php, tests/fixtures/controllers/return-type-declarations.php, tests/fixtures/drafts/return-type-declarations.yaml, tests/fixtures/models/return-type-declarations.php
=> Fix duplicate and missing return type declarations

src/Generators/FactoryGenerator.php, stubs/factory.stub, tests/fixtures/factories/nested-components.php, tests/fixtures/factories/nested-models.php
=> Append model namespace in the generated factory class.

src/Generators/MigrationGenerator.php, src/Generators/ModelGenerator.php, src/Generators/TestGenerator.php, src/Lexers/ModelLexer.php, tests/Feature/Generators/MigrationGeneratorTest.php, tests/Feature/Generators/TestGeneratorTest.php, tests/Feature/Lexers/ModelLexerTest.php, tests/fixtures/drafts/soft-deletes-respect-order.yaml, tests/fixtures/migrations/soft-deletes-respect-order.php
Deal with soft deletes in a different way, ensuring migrations respect the order or fields. Closes #485
=> Respect order for soft deletes. Closes #485

src/Generators/TestGenerator.php, tests/fixtures/tests/api-shorthand-validation.php, tests/fixtures/tests/certificate-pascal-case-example.php, tests/fixtures/tests/certificate-type-pascal-case-example.php, tests/fixtures/tests/full-crud-example.php
=> Replace assertDeleted with assertModelMissing

src/Generators/FactoryGenerator.php, tests/Feature/Generators/FactoryGeneratorTest.php, tests/fixtures/factories/shorthands.php
=> Fix literal `softdeletes` field

src/Concerns/HandlesImports.php, src/Concerns/HandlesTraits.php
Ran `pint` to fix any pending issues
=> Fix pint issues

config/blueprint.php, src/Generators/StatementGenerator.php, tests/Feature/Generators/Statements/EventGeneratorTest.php, tests/Feature/Generators/Statements/JobGeneratorTest.php, tests/Feature/Generators/Statements/MailGeneratorTest.php, tests/Feature/Generators/Statements/NotificationGeneratorTest.php, tests/fixtures/events/event-configured-with-constructor-property-promotion.php, tests/fixtures/jobs/job-configured-with-constructor-property-promotion.php, tests/fixtures/mailables/mail-configured-with-constructor-property-promotion.php, tests/fixtures/notifications/notification-configured-with-constructor-property-promotion.php
Resolves https://github.com/laravel-shift/blueprint/issues/618
=> Add support for constructor property promotion

src/Generators/MigrationGenerator.php, tests/fixtures/migrations/morphed-by-many-intermediate.php, tests/fixtures/migrations/polymorphic_relationships_images_table.php, tests/fixtures/migrations/polymorphic_relationships_images_table_multiple_morphto.php
https://laravel.com/docs/10.x/migrations#column-method-morphs
=> Use `morphs` instead of manually building columns

README.md, composer.json
Update symfony/yaml dependency to ^7.0 in order to allow install in a newly installed Laravel 10 application without needing to downgrade carbonphp/carbon-doctrine-types from 3.0.0 to 2.0.0
Updated Readme to reflect current Laravel version
=> Update for Laravel 10.x

src/Generators/Statements/FormRequestGenerator.php
Hi,
This PR fixes wrong column type in PHP Doc
=> Fix PHP Doc column type

src/Generators/MigrationGenerator.php, src/Generators/ModelGenerator.php, src/Models/Model.php, tests/Feature/BlueprintTest.php, tests/Feature/Generators/MigrationGeneratorTest.php, tests/fixtures/drafts/belongs-to-many-using-uuids.yaml, tests/fixtures/drafts/belongs-to-many.yaml, tests/fixtures/migrations/belongs-to-many-key-constraints-using-ulid-columns-diary-model.php, tests/fixtures/migrations/belongs-to-many-key-constraints-using-ulid-columns-journey-model.php, tests/fixtures/migrations/belongs-to-many-key-constraints-using-uuid-columns-diary-model.php, tests/fixtures/migrations/belongs-to-many-key-constraints-using-uuid-columns-journey-model.php, tests/fixtures/migrations/belongs-to-many-pivot-key-constraints-using-ulid-columns.php, tests/fixtures/migrations/belongs-to-many-pivot-key-constraints-using-uuid-columns.php
This is a rebuild of #661 which closes #659
=> Re-apply fixes from #661

src/Generators/FactoryGenerator.php, tests/Feature/Generators/FactoryGeneratorTest.php, tests/fixtures/drafts/with-enum.yaml, tests/fixtures/factories/with-enum.php
Fixes #691 but ensuring the factory uses a random element instead of a string / name
=> fix: enum in factory
